### ISSUE TITLE
PUT of a resource should allow to create relations to other resources

### ISSUE THREAD

**Issue by renardeau** [dimitrydhondt/inner-gerbil#23]
It should be possible to create relations together with creation of main resource i.e.
* When posting a party, it should be possible to also create corresponding partyrelations
* When posting a message, it should be possible to also create corresponding messageparties, messagetransactions and/or messagerelations
* When posting a transaction, it should be possible to also create transactionrelations??

It makes little sense to force the client to post each relation separately. Additinally, creating relation together with a resource allows to include both in same database transactions.

One way to implement this would be to use the afterinsert, afterupdate and afterdelete methods. Once implemented, we can also block the post and delete on relation resources

**Comment by dimitrydhondt** [comment]
Hi Bernard,

I think this is solved in SRI by using /batch operations. As described here : 
https://github.com/dimitrydhondt/sri#batch-operations

If that does not cover your case, please let me know :-)

Dimi

**Comment by eeemarv** [comment]
It makes sense to keep the api simple :-S

**Comment by renardeau** [comment]
@eeemarv 
Keeping api simple is nice, except if it makes (all) the client(s) more complex :-)

@dimitrydhondt 
The batch operation solves the issue of atomic operations, we can go that way.
But shouldn't we keep the API small? It is easier to extend an API than to reduce it (breaking retro-compatibility). Do we need to expose all those relations?

**Comment by eeemarv** [comment]
I'm for nice, clean and simple. I don't see how it makes clients more complex. The batch operation is ugly (mixing http methods). Why on earth not multiple simple requests? :-S

**Comment by dimitrydhondt** [comment]
Batch operations are provided to allow multiple operations to be atomic, and for optimizing overhead of multiple requests (although connection reuse on browsers optimizes as well, but practical  experience tells us batching is faster)

**Comment by dimitrydhondt** [comment]
Bernard, I think you are suggesting to not expose the relationships, but to use afterread/update/insert to *derive* the relationships from embedded information in the other resources. Is that the case?

**Comment by dimitrydhondt** [comment]
Multiple, individual requests are obviously still possible.  Usage of /batch is optional in some scenarios. But often using a batch for transaction scoping is a necessity.

**Comment by dimitrydhondt** [comment]
Yes, I understand. We have spent a lot of time discussing this some years back, and felt that simply exposing the relationships as resources was the easiest.

For example : If you want to translate an array of permalinks in the resource into the correct database operations, you need to do delta calculations.

So we restricted our APIs to the current style : 

- If the resource has a single reference to a related resource/node, and this is the primary update side, we use property: {href: "/othertype/guid" }. We did this from a pragmatic point-of-view, so that simply linking to another resource was easy. Think : simple hyperlink.
- In all other cases we expose the relationship/edge as a resource. This supports having multiple 1:n, n:m relationships/edges in a single style.

Especially with many to many relationships/edges it gets hairy trying to embed them in the nodes.

Also in sticking with viewing the domain model as a directed graph it makes sense to have nodes and edges as explicit resources.

https://en.wikipedia.org/wiki/Graph_(mathematics)

**Comment by renardeau** [comment]
Batch operation is working (but use relative paths !)
Discussed in hangout meeting ->ok to keep direct visibility on relations
